### ISSUE TITLE
Use of k8WatchNamespace (helm value parameter) leads to RBAC error 

### ISSUE THREAD

**Issue by nuno407** [hashicorp/terraform-helm#32]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### terraform-k8s, Helm, & Kubernetes Version

terraform-k8s: hashicorp/terraform-k8s:1.0.0
Helm: v3.6.0
Kubernetes:  v1.19.8-eks-96780e

### Helm Values

```yaml
syncWorkspace:
  k8WatchNamespace: dev
 ```

### Debug Output

`E0616 16:19:10.725113 1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/reflector.go:125: Failed to list *v1alpha1.Workspace: workspaces.app.terraform.io is forbidden: User "system:serviceaccount:terraform-operator:terraform-operator-terraform-sync-workspace" cannot list resource "workspaces" in API group "app.terraform.io" in the namespace "dev"`

### Expected Behavior

Terraform Cloud Operator is capable of watch and write secrets to the k8WatchNamespace defined namespace

### Actual Behavior

Terraform Operator logs that have no permissions for access resource "workspaces" in API group "app.terraform.io" in the namespace "dev".

### Steps to Reproduce

1. Use provided Helm values and install the operator in the "operator-terraform" namespace.

2. Apply the following YAML via kubectl apply (please note that the namespace is dev):

```yaml
apiVersion: app.terraform.io/v1alpha1
kind: Workspace
metadata:
  name: infra-dev
  namespace: dev
spec:
  organization: Bla
  secretsMountPath: "/tmp/secrets"
  module:
    source: "terraform-aws-modules/sqs/aws"
    version: "3.1.0"
  outputs:
    ......
  variables:
    ......
 ```
