### ISSUE TITLE
Add port to pod to allow prometheus-operator PodMonitor

### ISSUE THREAD

**Issue by nokernel** [hashicorp/terraform-helm#41]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add optional port definition to deployment's pod spec to allow prometheus-operator PodMonitor to scrape the /metrics endpoint.

### Potential Helm Configuration

```yaml
          {{- if .Values.syncWorkspace.exposeMetricsPort }}
          ports:
            - containerPort: 8383
              protocol: TCP
          {{- end }}
```
